name: remedi_flutter_base
description: Flutter Application templete project
version: 0.0.1
author: Remedi-DevTeam
homepage: https://remedi.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  stacked_mvvm:
    git:
      url: https://github.com/wooxist/stacked_mvvm.git
      ref: master

  # multi-resolution support.
  multiscreen: ^1.3.0

  # app version, build number and etc
  package_info: ^0.4.3+2

  # device info, os version, os type
  device_info: ^1.0.0

  # uuid generator and adid/idfa getter
  unique_ids: ^1.0.11

  # user-agent info.
  flutter_user_agent: ^1.2.2

  # save app contexts (uuid and etc)
  flutter_secure_storage: ^3.3.5

  # http
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  dio_firebase_performance: ^0.2.0

  # firebase
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_performance: ^0.4.3
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.4+1
  #firebase_remote_config: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
