name: remedi_flutter_plugin_splash
description: Flutter Application templete project
version: 0.0.1
author: Remedi-DevTeam
homepage: https://remedi.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  stacked_mvvm:
    git:
      url: https://github.com/studio-b-co-kr/stacked_mvvm.git
      ref: master

  # multi-resolution support.
  multiscreen: ^1.3.0

  # app version, build number and etc
  package_info: ^0.4.3+2

  # device info, os version, os type
  device_info: ^1.0.0

  # uuid generator and adid/idfa getter
  unique_ids: ^1.0.11

  # user-agent info.
  flutter_user_agent: ^1.2.2

  # save app contexts (uuid and etc)
  flutter_secure_storage: ^3.3.5

  # firebase
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_performance: ^0.4.3
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.4+1
  #firebase_remote_config: ^0.4.3

  # branch tracking and deep link
  flutter_branch_sdk: ^1.3.3

  #svg loader
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
